#使用方法
#指令/bcxx 消息编号 即可向所有玩家推送指定消息
#例如：/bcxx 1  则玩家会看到 12345
#编码请转为ANSI
#颜色代码符号&请用§代替
#作者：soutou 2015.12.19
1: §a12345
Note:
  - "&2你是傻逼吗？1 \n
  你是大傻逼吗？"
  - "&3你是傻逼吗？2"
  - "&4你是傻逼吗？3"
  - "&5你是傻逼吗？4"